### ISSUE TITLE
Problem with Component type

### ISSUE THREAD

**Issue by klaasnicolaas** [amitavroy/react-spa-laravel-typescript#6] opened 2020-06-12 00:52 UTC
![image](https://user-images.githubusercontent.com/20448157/84452800-24567700-ac57-11ea-97fc-aaaedec11779.png)

I followed all your videos to create a react login that connects to a Laravel API. However, I now encounter an error that I can't get rid of. _"Binding element 'Component' implicitly has an 'any' type. | ts(7031)"_

Inside this file: [here](https://github.com/amitavroy/react-spa-laravel-typescript/blob/master/client/src/components/common/router/protected/index.tsx)

Maybe you know the solution?

**Comment by amitavroy** [comment] 2020-06-12 03:58
Have you clone my repo? 
Do yo usee any change in this file: https://github.com/amitavroy/react-spa-laravel-typescript/blob/master/client/tsconfig.json

Line number 13

**Comment by klaasnicolaas** [comment] 2020-06-12 10:52
No I didn't clone the repo.
I finally solved the problem by converting the file from `index.tsx` to `index.jsx`, just don't understand why it makes a difference between Typescript or Javascript 🤔

**Comment by amitavroy** [comment] 2020-06-12 11:49
The problem you were facing looks more likely to be strict hinting. Hence, do try the thing that I mentioned once and check. Ideally, it should work. 

If you are doing the project in TypeScript, then it's best to work with that. And not use jsx :)

Anyways, closing the comment as you are now able to work.

**Closed as completed by amitavroy** 2020-06-12 11:49 UTC

**Comment by klaasnicolaas** [comment] 2020-06-12 12:45
Have another problem that I am facing now.

After clicking login I do see my token in the console, but I am not redirected to the protected page. Only when I refresh afterwards and log in again will I succeed 🤔 

BTW change "strict" to false in `tsconfig.json` did also fix my problem 😄

**Comment by amitavroy** [comment] 2020-06-12 13:31
Yes, this is a known issue. I have also faced this problem and I don't think I know exactly what the problem is.

**Comment by klaasnicolaas** [comment] 2020-06-12 13:55
As far as I have been able to debug, react still thinks that you are not authenticated after pressing the login button, only after a refresh and if the token is already present you will get to your dashboard.

EDIT: little more debugging: it seems that `auth.isAuthenticated()` isn't updating to `true`

**Comment by klaasnicolaas** [comment] 2020-06-13 19:08
@amitavroy I found a kind of fix for the login problem 🥳 

In [this file](https://github.com/amitavroy/react-spa-laravel-typescript/blob/master/client/src/pages/login/index.tsx) add: (between these lines)

```js
AuthService.handleLoginSuccess(response, this.state.isChecked);
auth.authenticated = true; // This line
this.props.history.push("/home");
```
and import the protected auth file. Maybe this works for you too?
